"""
Report Generators — exportable artifacts for both audiences.

  * postmortem_markdown()  — per-incident blameless postmortem (engineer)
  * exec_report_markdown() — reliability briefing (management)

Markdown so it pastes cleanly into Confluence, ServiceNow work notes, Slack,
or converts to PDF/Word without extra dependencies.
"""

from datetime import datetime, timezone

from .correlation import Incident


def _fmt(ts: float | None) -> str:
    if not ts:
        return "—"
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def postmortem_markdown(inc: Incident, brief=None, remediation=None,
                        topology=None, ticket=None, jira_issue=None) -> str:
    duration = ((inc.resolved_ts - inc.created_ts) / 60
                if inc.resolved_ts else None)
    blast = (topology.downstream_of(inc.probable_root_cause)
             if topology and inc.probable_root_cause else [])

    lines = [
        f"# Postmortem — {inc.incident_id}",
        "",
        f"**Title:** {inc.title}  ",
        f"**Severity:** {inc.severity.upper()}  ",
        f"**Business service:** {inc.business_service or 'Unmapped'}  ",
        f"**Detected:** {_fmt(inc.created_ts)}  ",
        f"**Resolved:** {_fmt(inc.resolved_ts)}  ",
        f"**Duration:** {f'{duration:.0f} minutes' if duration else 'ongoing'}  ",
        f"**Status:** {inc.status}",
    ]
    if ticket or jira_issue:
        lines.append("")
        lines.append("## Tracking")
        if ticket:
            lines.append(f"- ServiceNow: **{ticket.number}** ({ticket.state})")
        if jira_issue:
            lines.append(f"- Jira: **[{jira_issue.key}]({jira_issue.url})** "
                         f"— filed as {jira_issue.reason.replace('_', ' ')}")
        elif ticket:
            lines.append("- Jira: not filed (doesn't currently qualify as "
                         "automation gap or SLA breach)")
    lines += [
        "",
        "## Impact",
        f"- Configuration items affected: {len(inc.impacted_cis)} "
        f"({', '.join(inc.impacted_cis)})",
        f"- Downstream blast radius: {len(blast)} CI(s)" if blast else
        "- Downstream blast radius: none identified",
        f"- Raw alerts correlated into this incident: {inc.raw_alert_count}",
        "",
        "## Root cause",
        f"Probable root cause: **{inc.probable_root_cause or 'not determined'}**",
        "",
    ]

    if brief:
        lines += [brief.rca_narrative, ""]

    lines += ["## Timeline", "",
              "| Time | Event | CI | Severity | Occurrences |",
              "|---|---|---|---|---|"]
    for e in sorted(inc.events, key=lambda x: x.first_ts):
        lines.append(f"| {_fmt(e.first_ts)} | {e.metric} | {e.ci_id} | "
                     f"{e.severity} | {e.count} |")
    if inc.resolved_ts:
        lines.append(f"| {_fmt(inc.resolved_ts)} | Auto-remediation verified | "
                     f"{inc.probable_root_cause or '—'} | — | — |")

    lines += ["", "## Response"]
    if remediation:
        lines.append(f"Runbook executed: **{remediation.runbook_name}** "
                     f"({'succeeded' if remediation.success else 'FAILED'})")
        lines.append("")
        lines.append("```")
        lines += list(remediation.log)
        lines.append("```")
    elif inc.remediation:
        lines.append(f"Remediation: {inc.remediation}")
    else:
        lines.append("No automated runbook matched — handled manually. "
                     "This incident is an automation-backlog candidate.")

    lines += ["", "## Follow-up actions", ""]
    if brief and brief.recommendations:
        for i, rec in enumerate(brief.recommendations, 1):
            lines.append(f"{i}. [ ] {rec}")
    else:
        lines += ["1. [ ] Review detection thresholds for the affected metrics.",
                  "2. [ ] Confirm runbook verification criteria were adequate.",
                  "3. [ ] Assess whether blast radius warrants topology changes."]

    lines += ["", "---",
              "*Generated by CloudOps-AI. Blameless review: focus on systems and "
              "signals, not individuals.*"]
    return "\n".join(lines)


def itsm_report_markdown(tickets, period_label: str = "current window",
                         sla_hours: dict | None = None, jira_issues=None) -> str:
    """Ticket-centric summary report. `sla_hours` maps impact ("1"/"2"/"3")
    to a resolution-time target in hours; defaults to the standard
    1/4/8h P1/P2/P3 targets used elsewhere in the app. `jira_issues`, if
    supplied, is the list of JiraIssue objects synced this session
    (core.jira.sync_to_jira output) — surfaced here so the engineering
    backlog and the ticket summary are always read from the one report."""
    sla_hours = sla_hours or {"1": 1.0, "2": 4.0, "3": 8.0}
    now = datetime.now(timezone.utc).timestamp()

    total = len(tickets)
    open_n = sum(1 for t in tickets if t.state != "Resolved")
    resolved = [t for t in tickets if t.state == "Resolved" and t.resolved_at]
    res_minutes = [(t.resolved_at - t.opened_at) / 60 for t in resolved]
    mttr = sum(res_minutes) / len(res_minutes) if res_minutes else None

    def _breached(t) -> bool:
        limit_h = sla_hours.get(t.impact, 8.0)
        elapsed_h = ((t.resolved_at or now) - t.opened_at) / 3600
        return elapsed_h > limit_h

    breaches = [t for t in tickets if _breached(t)]

    lines = [
        "# ITSM Ticket Summary",
        f"*Period: {period_label} · generated "
        f"{datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
        "## Headline metrics", "",
        "| Metric | Value |", "|---|---|",
        f"| Total tickets | {total} |",
        f"| Open | {open_n} |",
        f"| Resolved | {total - open_n} |",
        f"| MTTR | {f'{mttr:.0f} min' if mttr is not None else '—'} |",
        f"| SLA breaches | {len(breaches)} |",
        "",
    ]

    by_impact: dict[str, int] = {}
    by_service: dict[str, int] = {}
    for t in tickets:
        by_impact[t.impact] = by_impact.get(t.impact, 0) + 1
        svc = t.business_service or "Unmapped"
        by_service[svc] = by_service.get(svc, 0) + 1

    lines += ["## By impact (priority)", "",
              "| Impact | Count |", "|---|---|"]
    for imp in sorted(by_impact):
        lines.append(f"| P{imp} | {by_impact[imp]} |")

    lines += ["", "## By business service", "",
              "| Service | Tickets |", "|---|---|"]
    for svc, n in sorted(by_service.items(), key=lambda kv: -kv[1]):
        lines.append(f"| {svc} | {n} |")

    lines += ["", "## SLA breaches", ""]
    if breaches:
        lines += ["| Ticket | Impact | Service | State | Age/Resolution |",
                  "|---|---|---|---|---|"]
        for t in sorted(breaches, key=lambda x: x.opened_at)[:20]:
            elapsed_min = ((t.resolved_at or now) - t.opened_at) / 60
            lines.append(f"| {t.number} | P{t.impact} | "
                         f"{t.business_service or 'Unmapped'} | {t.state} | "
                         f"{elapsed_min:.0f} min |")
    else:
        lines.append("No SLA breaches — every ticket resolved (or is tracking) "
                     "within its impact-based target.")

    lines += ["", "---",
              "*Generated by CloudOps-AI. SLA targets: P1=1h, P2=4h, P3=8h "
              "unless configured otherwise.*"]

    if jira_issues:
        lines.insert(-2, "## Engineering backlog synced to Jira")
        lines.insert(-2, "")
        lines.insert(-2, "| Jira Key | Incident | SN Ticket | Reason |")
        lines.insert(-2, "|---|---|---|---|")
        for i in jira_issues:
            lines.insert(-2, f"| {i.key} | {i.incident_id} | {i.sn_ticket_number} | "
                             f"{i.reason.replace('_', ' ')} |")
        lines.insert(-2, "")

    return "\n".join(lines)


def exec_report_markdown(kpi, stats, slo_statuses, scorecard, gaps,
                         hotspots=None, period_label: str = "current window") -> str:
    lines = [
        "# Reliability Briefing",
        f"*Period: {period_label} · generated "
        f"{datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
        "## Headline metrics", "",
        "| Metric | Value |", "|---|---|",
    ]
    for k, v in kpi.to_dict().items():
        lines.append(f"| {k} | {v} |")

    lines += ["", "## Signal-to-noise", "",
              f"- {stats['raw_alerts']} raw alerts reduced to "
              f"{stats['incidents']} actionable incidents "
              f"(**{stats['noise_reduction_pct']}%** noise eliminated).",
              f"- Correlation collapsed them into {stats['deduped_events']} "
              f"deduplicated events before topology grouping.",
              ""]

    if slo_statuses:
        lines += ["## Error budget status", "",
                  "| SLO | Target | Achieved | Budget used | Burn rate | Status | Action |",
                  "|---|---|---|---|---|---|---|"]
        for s in slo_statuses:
            lines.append(
                f"| {s.slo.name} | {s.slo.target_pct}% | {s.achieved_pct}% | "
                f"{s.consumed_pct}% | {s.burn_rate}x | **{s.status}** | {s.action} |")
        lines.append("")

    if scorecard:
        lines += ["## Service health scorecard", "",
                  "| Service | Grade | Score | Incidents | Critical | Auto-resolved | Open |",
                  "|---|---|---|---|---|---|---|"]
        for s in scorecard:
            lines.append(f"| {s.business_service} | **{s.grade}** | {s.health_score} | "
                         f"{s.incidents} | {s.critical} | {s.auto_resolved} | "
                         f"{s.open_items} |")
        lines.append("")

    if gaps:
        total_toil = sum(g.est_annual_toil_hours for g in gaps)
        lines += ["## Automation backlog", "",
                  f"{len(gaps)} incident pattern(s) had no matching runbook, "
                  f"representing an estimated **{total_toil:.0f} hours/year** of "
                  f"manual toil.", "",
                  "| Incident | Metrics | Severity | Est. annual toil |",
                  "|---|---|---|---|"]
        for g in gaps[:10]:
            lines.append(f"| {g.incident_id} | {', '.join(g.metrics)} | "
                         f"{g.severity} | {g.est_annual_toil_hours}h |")
        lines.append("")
    else:
        lines += ["## Automation backlog", "",
                  "Full runbook coverage — every incident matched an "
                  "auto-remediation path.", ""]

    if hotspots:
        lines += ["## Alert tuning opportunities", "",
                  "| CI | Metric | Alerts | % of volume | Recommendation |",
                  "|---|---|---|---|---|"]
        for h in hotspots[:5]:
            lines.append(f"| {h.ci_id} | {h.metric} | {h.alert_count} | "
                         f"{h.pct_of_total}% | {h.recommendation} |")
        lines.append("")

    lines += ["---",
              "*Generated by CloudOps-AI. Figures derive from the current "
              "analysis window; MTTR reflects the configured data source.*"]
    return "\n".join(lines)
