"""
Report Generators — exportable artifacts for both audiences.

  * postmortem_markdown()  — per-incident blameless postmortem (engineer)
  * exec_report_markdown() — reliability briefing (management)

Markdown so it pastes cleanly into Confluence, ServiceNow work notes, Slack,
or converts to PDF/Word without extra dependencies.
"""

from datetime import datetime, timezone

from .correlation import Incident


def _fmt(ts: float | None) -> str:
    if not ts:
        return "—"
    return datetime.fromtimestamp(ts, tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")


def postmortem_markdown(inc: Incident, brief=None, remediation=None,
                        topology=None) -> str:
    duration = ((inc.resolved_ts - inc.created_ts) / 60
                if inc.resolved_ts else None)
    blast = (topology.downstream_of(inc.probable_root_cause)
             if topology and inc.probable_root_cause else [])

    lines = [
        f"# Postmortem — {inc.incident_id}",
        "",
        f"**Title:** {inc.title}  ",
        f"**Severity:** {inc.severity.upper()}  ",
        f"**Business service:** {inc.business_service or 'Unmapped'}  ",
        f"**Detected:** {_fmt(inc.created_ts)}  ",
        f"**Resolved:** {_fmt(inc.resolved_ts)}  ",
        f"**Duration:** {f'{duration:.0f} minutes' if duration else 'ongoing'}  ",
        f"**Status:** {inc.status}",
        "",
        "## Impact",
        f"- Configuration items affected: {len(inc.impacted_cis)} "
        f"({', '.join(inc.impacted_cis)})",
        f"- Downstream blast radius: {len(blast)} CI(s)" if blast else
        "- Downstream blast radius: none identified",
        f"- Raw alerts correlated into this incident: {inc.raw_alert_count}",
        "",
        "## Root cause",
        f"Probable root cause: **{inc.probable_root_cause or 'not determined'}**",
        "",
    ]

    if brief:
        lines += [brief.rca_narrative, ""]

    lines += ["## Timeline", "",
              "| Time | Event | CI | Severity | Occurrences |",
              "|---|---|---|---|---|"]
    for e in sorted(inc.events, key=lambda x: x.first_ts):
        lines.append(f"| {_fmt(e.first_ts)} | {e.metric} | {e.ci_id} | "
                     f"{e.severity} | {e.count} |")
    if inc.resolved_ts:
        lines.append(f"| {_fmt(inc.resolved_ts)} | Auto-remediation verified | "
                     f"{inc.probable_root_cause or '—'} | — | — |")

    lines += ["", "## Response"]
    if remediation:
        lines.append(f"Runbook executed: **{remediation.runbook_name}** "
                     f"({'succeeded' if remediation.success else 'FAILED'})")
        lines.append("")
        lines.append("```")
        lines += list(remediation.log)
        lines.append("```")
    elif inc.remediation:
        lines.append(f"Remediation: {inc.remediation}")
    else:
        lines.append("No automated runbook matched — handled manually. "
                     "This incident is an automation-backlog candidate.")

    lines += ["", "## Follow-up actions", ""]
    if brief and brief.recommendations:
        for i, rec in enumerate(brief.recommendations, 1):
            lines.append(f"{i}. [ ] {rec}")
    else:
        lines += ["1. [ ] Review detection thresholds for the affected metrics.",
                  "2. [ ] Confirm runbook verification criteria were adequate.",
                  "3. [ ] Assess whether blast radius warrants topology changes."]

    lines += ["", "---",
              "*Generated by CloudOps-AI. Blameless review: focus on systems and "
              "signals, not individuals.*"]
    return "\n".join(lines)


def exec_report_markdown(kpi, stats, slo_statuses, scorecard, gaps,
                         hotspots=None, period_label: str = "current window") -> str:
    lines = [
        "# Reliability Briefing",
        f"*Period: {period_label} · generated "
        f"{datetime.now(tz=timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*",
        "",
        "## Headline metrics", "",
        "| Metric | Value |", "|---|---|",
    ]
    for k, v in kpi.to_dict().items():
        lines.append(f"| {k} | {v} |")

    lines += ["", "## Signal-to-noise", "",
              f"- {stats['raw_alerts']} raw alerts reduced to "
              f"{stats['incidents']} actionable incidents "
              f"(**{stats['noise_reduction_pct']}%** noise eliminated).",
              f"- Correlation collapsed them into {stats['deduped_events']} "
              f"deduplicated events before topology grouping.",
              ""]

    if slo_statuses:
        lines += ["## Error budget status", "",
                  "| SLO | Target | Achieved | Budget used | Burn rate | Status | Action |",
                  "|---|---|---|---|---|---|---|"]
        for s in slo_statuses:
            lines.append(
                f"| {s.slo.name} | {s.slo.target_pct}% | {s.achieved_pct}% | "
                f"{s.consumed_pct}% | {s.burn_rate}x | **{s.status}** | {s.action} |")
        lines.append("")

    if scorecard:
        lines += ["## Service health scorecard", "",
                  "| Service | Grade | Score | Incidents | Critical | Auto-resolved | Open |",
                  "|---|---|---|---|---|---|---|"]
        for s in scorecard:
            lines.append(f"| {s.business_service} | **{s.grade}** | {s.health_score} | "
                         f"{s.incidents} | {s.critical} | {s.auto_resolved} | "
                         f"{s.open_items} |")
        lines.append("")

    if gaps:
        total_toil = sum(g.est_annual_toil_hours for g in gaps)
        lines += ["## Automation backlog", "",
                  f"{len(gaps)} incident pattern(s) had no matching runbook, "
                  f"representing an estimated **{total_toil:.0f} hours/year** of "
                  f"manual toil.", "",
                  "| Incident | Metrics | Severity | Est. annual toil |",
                  "|---|---|---|---|"]
        for g in gaps[:10]:
            lines.append(f"| {g.incident_id} | {', '.join(g.metrics)} | "
                         f"{g.severity} | {g.est_annual_toil_hours}h |")
        lines.append("")
    else:
        lines += ["## Automation backlog", "",
                  "Full runbook coverage — every incident matched an "
                  "auto-remediation path.", ""]

    if hotspots:
        lines += ["## Alert tuning opportunities", "",
                  "| CI | Metric | Alerts | % of volume | Recommendation |",
                  "|---|---|---|---|---|"]
        for h in hotspots[:5]:
            lines.append(f"| {h.ci_id} | {h.metric} | {h.alert_count} | "
                         f"{h.pct_of_total}% | {h.recommendation} |")
        lines.append("")

    lines += ["---",
              "*Generated by CloudOps-AI. Figures derive from the current "
              "analysis window; MTTR reflects the configured data source.*"]
    return "\n".join(lines)
